# Generated by Django 5.2.1 on 2025-05-15 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contactsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
