# Generated by Django 5.2.1 on 2025-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('business_type', models.CharField(max_length=100)),
                ('years_in_business', models.PositiveIntegerField()),
                ('business_description', models.TextField()),
                ('business_documents', models.FileField(blank=True, null=True, upload_to='vendor_documents/')),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('agreed_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
