# Generated by Django 5.2.1 on 2025-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contactsmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
