# Generated by Django 5.2.1 on 2025-05-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.TextField(default='no review'),
            preserve_default=False,
        ),
    ]
