# Generated by Django 5.2.1 on 2025-05-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Registeredvendor',
        ),
    ]
