# Generated by Django 5.2.1 on 2025-05-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.registeredvendor'),
        ),
    ]
