# Generated by Django 5.2.1 on 2025-05-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendors.package'),
        ),
    ]
