# Generated by Django 5.2.1 on 2025-05-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_packageimage_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
